# Banking Fraud Detection & Loan Risk Analysis

## Objective

The objective of this project is to analyze banking transaction data to identify patterns related to financial activities, potential fraud indicators, and loan distribution among customers. The analysis focuses on understanding customer behavior, transaction trends, and financial risk patterns by examining banking transactions, account activity, customer demographics, and loan records.

This project aims to explore how different financial factors such as transaction volume, customer profile, branch activity, and loan attributes influence banking operations and potential fraud risks.

# Dataset Overview

The dataset used in this project consists of multiple relational tables representing a simulated banking system. These datasets include information about customers, accounts, transactions, loans, and bank branches. We have merged the datasets to create a master analytical dataset that enables comprehensive financial data analysis.

The merged dataset allows us the analysis of relationships between customer information, account activity, transaction behavior, and loan records.

# Key Dataset Characteristics

Coverage:  Banking transactions across multiple branches and customers

Data Format: Multiple CSV files
- customer_types.csv
- accounts.csv
- loans.csv
- transactions.csv
- customer_types.csv
- account_types.csv
- account_statuses.csv
- account_statuses.csv
- transaction_types.csv
- branches.csv
- addresses.csv
  
Data Source: Kaggle

## Types of Variables Included in the Dataset

The dataset contains several categories of variables:

#### 1. Transaction Information

Transaction ID
Transaction date
Transaction amount
Transaction type
Account origin and destination IDs
Transaction description

These variables help analyze transaction behavior and financial activity patterns.

#### 2. Customer Information

Customer ID
First name and last name
Date of birth
Customer type

These variables help analyze customer demographics and financial behavior patterns.

#### 3. Account Information

Account ID
Account type
Account status
Account balance
Account opening date

These variables provide insight into banking account activity and account status.

#### 4. Branch Information

Branch name
Branch ID

Branch-related variables help analyze regional banking activity and transaction distribution across branches.

#### 5. Geographic Information

Street address
City
Country

These variables allow geographic analysis of banking activity across different locations.

#### 6. Loan Information

Loan ID
Loan status
Principal loan amount
Interest rate
Loan start date
Loan estimated end date

### Step 1: Importing the Required Libraries
- **Pandas** – data manipulation and analysis  
- **NumPy** – numerical operations  
- **Matplotlib & Seaborn** – data visualization

In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Step 2: Data Loading

In [62]:
account_status = pd.read_csv("C:/Users/shubh/Desktop/Simran/Project/Prodigy-info-tech/Project-2/Finance_Fraud&Loan_Dataset/account_statuses.csv")
account_types = pd.read_csv("C:/Users/shubh/Desktop/Simran/Project/Prodigy-info-tech/Project-2/Finance_Fraud&Loan_Dataset/account_types.csv")
accounts = pd.read_csv("C:/Users/shubh/Desktop/Simran/Project/Prodigy-info-tech/Project-2/Finance_Fraud&Loan_Dataset/accounts.csv")
addresses = pd.read_csv("C:/Users/shubh/Desktop/Simran/Project/Prodigy-info-tech/Project-2/Finance_Fraud&Loan_Dataset/addresses.csv")
branches = pd.read_csv("C:/Users/shubh/Desktop/Simran/Project/Prodigy-info-tech/Project-2/Finance_Fraud&Loan_Dataset/branches.csv")
customer_types = pd.read_csv("C:/Users/shubh/Desktop/Simran/Project/Prodigy-info-tech/Project-2/Finance_Fraud&Loan_Dataset/customer_types.csv")
customers = pd.read_csv("C:/Users/shubh/Desktop/Simran/Project/Prodigy-info-tech/Project-2/Finance_Fraud&Loan_Dataset/customers.csv")
loan_status = pd.read_csv("C:/Users/shubh/Desktop/Simran/Project/Prodigy-info-tech/Project-2/Finance_Fraud&Loan_Dataset/loan_statuses.csv")
loans = pd.read_csv("C:/Users/shubh/Desktop/Simran/Project/Prodigy-info-tech/Project-2/Finance_Fraud&Loan_Dataset/loans.csv")
transaction_types = pd.read_csv("C:/Users/shubh/Desktop/Simran/Project/Prodigy-info-tech/Project-2/Finance_Fraud&Loan_Dataset/transaction_types.csv")
transactions = pd.read_csv("C:/Users/shubh/Desktop/Simran/Project/Prodigy-info-tech/Project-2/Finance_Fraud&Loan_Dataset/transactions.csv")

# Step 3: Merging the datasets

The project originally consisted of multiple CSV files representing different components of a banking system. These datasets were merged using key identifiers such as, CustomerID, AccountID,TransactionTypeID, LoanID, BranchID to create a unified dataset for analysis.

## 3.1 Merge Customer Information

In [63]:
customer_df = customers.merge(customer_types,on='CustomerTypeID',how='left')

customer_df = customer_df.merge(addresses,on='AddressID',how='left')

**The customers dataset was merged with the customer_types dataset using the CustomerTypeID to include information about the type of each customer. Then, the resulting dataset was merged with the addresses dataset using AddressID to add location details such as street, city, and country for each customer.**

## 3.2 Merge Account Information

In [64]:
account_df = accounts.merge(account_types, on='AccountTypeID',how='left')

account_df = account_df.merge(account_status, on='AccountStatusID',how='left')

**The accounts dataset was merged with the account_types dataset using AccountTypeID to include information about the type of each account. Then, the resulting dataset was merged with the account_status dataset using AccountStatusID to add details about the current status of each account.**

## 3.3 Merge Transcations

In [65]:
transactions_df = transactions.merge(transaction_types, on='TransactionTypeID', how='left')

transactions_df = transactions_df.merge(branches, on='BranchID', how='left')

**The transactions dataset was merged with the transaction_types dataset using TransactionTypeID to include the type of each transaction. Then, the resulting dataset was merged with the branches dataset using BranchID to add information about the branch where the transaction occurred.**

## 3.4 Merge Transactions with Accounts

In [66]:
transactions_df = transactions_df.merge(account_df, left_on='AccountOriginID', right_on='AccountID',how='left')

**The transactions_df dataset was merged with the account_df dataset using AccountOriginID from the transactions table and AccountID from the accounts table. This merge adds account-related information such as account type, account status, and balance to each transaction record**

## 3.5 Merge Customers with Transactions

In [67]:
master_df = transactions_df.merge(customer_df, on='CustomerID',how='left')

**The transactions_df dataset was merged with the customer_df dataset using CustomerID to include customer-related information for each transaction. This merge adds details such as the customer's name, demographic information, and address to the transaction records.**

## 3.6 Merge Loan Data

In [68]:
loan_df = loans.merge(loan_status, on='LoanStatusID',how='left')

master_df = master_df.merge(loan_df, on='AccountID', how='left')

**The loans dataset was merged with the loan_status dataset using LoanStatusID to include information about the status of each loan. Then, the resulting loan_df was merged with the master_df using AccountID to add loan details such as loan amount, interest rate, and loan status to the master dataset.**

In [69]:
df = master_df
df.to_csv("C:/Users/shubh/Desktop/Simran/Project/Prodigy-info-tech/Project-2/Finance_Fraud&Loan_Dataset/finance_Fraud_master_dataset.csv",index=False)

**The final merged dataset was assigned to the variable df, creating a master dataframe for further analysis and preprocessing. This dataframe was then exported as a CSV file to the specified directory using to_csv(), allowing the integrated dataset to be saved for future use.**

### Step 4: Loading the Master Dataset

In [70]:
path = "C:/Users/shubh/Desktop/Simran/Project/Prodigy-info-tech/Project-2/Finance_Fraud&Loan_Dataset/finance_Fraud_master_dataset.csv"

In [71]:
df = pd.read_csv(path)
print(df)

       TransactionID  AccountOriginID  AccountDestinationID  \
0            3022681           201164                200868
1            3037846           200138                201402
2            3045293           201002                201180
3            3017397           201066                201144
4            3016750           200289                201413
...              ...              ...                   ...
54950        3028219           200513                200603
54951        3047099           200658                201078
54952        3009955           200045                200942
54953        3018946           201361                200162
54954        3018946           201361                200162

       TransactionTypeID   Amount             TransactionDate  BranchID  \
0                      2   855.17  2023-04-20 02:00:00.000000        41
1                      2   806.20  2021-08-10 15:00:00.000000        43
2                      1  1229.44  2020-08-16 03:00:00.000000         5
3                      4  4441.60  2021-10-10 06:00:00.000000        14
4                      3  2526.20  2022-07-28 00:00:00.000000        37
...                  ...      ...                         ...       ...
54950                  1  1507.27  2021-11-18 12:00:00.000000         3
54951                  2  1998.06                         NaN         8
54952                  4  4242.71  2020-06-20 09:00:00.000000        24
54953                  1  4254.94                         NaN        16
54954                  1  4254.94                         NaN        16

             Description  TypeName_x BranchName  ...           Street  \
0      Transaction 22681  Withdrawal  Branch 41  ...             East
1      Transaction 37846  Withdrawal  Branch 43  ...           Felton
2      Transaction 45293     Deposit   Branch 5  ...           Waller
3      Transaction 17397     Payment  Branch 14  ...           Thomas
4      Transaction 16750    Transfer  Branch 37  ...        Rodriguez
...                  ...         ...        ...  ...              ...
54950  Transaction 28219     Deposit   Branch 3  ...            Wiese
54951  Transaction 47099  Withdrawal   Branch 8  ...      Shakespeare
54952   Transaction 9955     Payment  Branch 24  ...     Walter U Lum
54953  Transaction 18946     Deposit  Branch 16  ...  Cesar Chavez On
54954  Transaction 18946     Deposit  Branch 16  ...  Cesar Chavez On

                 City        Country    LoanID  LoanStatusID  PrincipalAmount  \
0         Tinley Park  United States  400173.0           1.0         72030.09
1               Camas  United States       NaN           NaN              NaN
2      Mount Pleasant  United States       NaN           NaN              NaN
3              Walnut  United States       NaN           NaN              NaN
4             Rocklin  United States       NaN           NaN              NaN
...               ...            ...       ...           ...              ...
54950  Mount Pleasant  United States       NaN           NaN              NaN
54951      Round Lake  United States       NaN           NaN              NaN
54952   Central Point  United States       NaN           NaN              NaN
54953         Newberg  United States  400322.0           1.0         79157.89
54954         Newberg  United States  400322.0           1.0         79157.89

      InterestRate                   StartDate            EstimatedEndDate  \
0           0.0789  2022-08-23 00:00:00.000000  2026-12-19 00:00:00.000000
1              NaN                         NaN                         NaN
2              NaN                         NaN                         NaN
3              NaN                         NaN                         NaN
4              NaN                         NaN                         NaN
...            ...                         ...                         ...
54950          NaN                         NaN                         NaN
54951          NaN                         NaN                         NaN
54952          NaN                         NaN                         NaN
54953       0.1236  2023-02-20 00:00:00.000000  2025-03-18 00:00:00.000000
54954       0.1236  2023-02-20 00:00:00.000000  2025-03-18 00:00:00.000000

      StatusName_y
0           Active
1              NaN
2              NaN
3              NaN
4              NaN
...            ...
54950          NaN
54951          NaN
54952          NaN
54953       Active
54954       Active

[54955 rows x 35 columns]

Type name X - Transcation type - Deposit, Withdrawal, Trander, Payment
Status Name Y - Loan Status - Active, paid off, Overdue

### Step 5: Initial Data 
Before performing the data cleaning, it is important to inspect the structure and data quality.

#### 5.1 Checking the dataset shape

In [72]:
df.shape

(54955, 35)

#### 5.2 Checking the first few rows

In [73]:
df.head()

,TransactionID,AccountOriginID,AccountDestinationID,TransactionTypeID,Amount,TransactionDate,BranchID,Description,TypeName_x,BranchName,...,Street,City,Country,LoanID,LoanStatusID,PrincipalAmount,InterestRate,StartDate,EstimatedEndDate,StatusName_y
0,3022681,201164,200868,2,855.17,2023-04-20 02:00:00.000000,41,Transaction 22681,Withdrawal,Branch 41,...,East,Tinley Park,United States,400173.0,1.0,72030.09,0.0789,2022-08-23 00:00:00.000000,2026-12-19 00:00:00.000000,Active
1,3037846,200138,201402,2,806.20,2021-08-10 15:00:00.000000,43,Transaction 37846,Withdrawal,Branch 43,...,Felton,Camas,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3045293,201002,201180,1,1229.44,2020-08-16 03:00:00.000000,5,Transaction 45293,Deposit,Branch 5,...,Waller,Mount Pleasant,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3017397,201066,201144,4,4441.60,2021-10-10 06:00:00.000000,14,Transaction 17397,Payment,Branch 14,...,Thomas,Walnut,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3016750,200289,201413,3,2526.20,2022-07-28 00:00:00.000000,37,Transaction 16750,Transfer,Branch 37,...,Rodriguez,Rocklin,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### 5.3 Checking the last few rows

In [74]:
df.tail()

,TransactionID,AccountOriginID,AccountDestinationID,TransactionTypeID,Amount,TransactionDate,BranchID,Description,TypeName_x,BranchName,...,Street,City,Country,LoanID,LoanStatusID,PrincipalAmount,InterestRate,StartDate,EstimatedEndDate,StatusName_y
54950,3028219,200513,200603,1,1507.27,2021-11-18 12:00:00.000000,3,Transaction 28219,Deposit,Branch 3,...,Wiese,Mount Pleasant,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54951,3047099,200658,201078,2,1998.06,NaN,8,Transaction 47099,Withdrawal,Branch 8,...,Shakespeare,Round Lake,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54952,3009955,200045,200942,4,4242.71,2020-06-20 09:00:00.000000,24,Transaction 9955,Payment,Branch 24,...,Walter U Lum,Central Point,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54953,3018946,201361,200162,1,4254.94,NaN,16,Transaction 18946,Deposit,Branch 16,...,Cesar Chavez On,Newberg,United States,400322.0,1.0,79157.89,0.1236,2023-02-20 00:00:00.000000,2025-03-18 00:00:00.000000,Active
54954,3018946,201361,200162,1,4254.94,NaN,16,Transaction 18946,Deposit,Branch 16,...,Cesar Chavez On,Newberg,United States,400322.0,1.0,79157.89,0.1236,2023-02-20 00:00:00.000000,2025-03-18 00:00:00.000000,Active

#### 5.4 Checking the Column names

In [75]:
df.columns

Index(['TransactionID', 'AccountOriginID', 'AccountDestinationID',
       'TransactionTypeID', 'Amount', 'TransactionDate', 'BranchID',
       'Description', 'TypeName_x', 'BranchName', 'AddressID_x', 'AccountID',
       'CustomerID', 'AccountTypeID', 'AccountStatusID', 'Balance',
       'OpeningDate', 'TypeName_y', 'StatusName_x', 'FirstName', 'LastName',
       'DateOfBirth', 'AddressID_y', 'CustomerTypeID', 'TypeName', 'Street',
       'City', 'Country', 'LoanID', 'LoanStatusID', 'PrincipalAmount',
       'InterestRate', 'StartDate', 'EstimatedEndDate', 'StatusName_y'],
      dtype='object')

#### 5.5 Statistical Summary of Data

In [76]:
df.describe()

,TransactionID,AccountOriginID,AccountDestinationID,TransactionTypeID,Amount,BranchID,AddressID_x,AccountID,CustomerID,AccountTypeID,AccountStatusID,Balance,AddressID_y,CustomerTypeID,LoanID,LoanStatusID,PrincipalAmount,InterestRate
count,5.495500e+04,54955.000000,54955.000000,54955.000000,54955.000000,54955.000000,54955.000000,54955.000000,54955.000000,54955.000000,54955.000000,54955.000000,54955.000000,54955.000000,11219.000000,11219.000000,11219.000000,11219.000000
mean,3.024714e+06,200820.305468,200820.036666,2.192357,2503.939607,25.626949,540.203075,200820.305468,10557.171176,3.053171,1.241743,48895.446419,638.250350,2.063361,400164.456190,1.381674,51748.272473,0.088469
std,1.430076e+04,478.761897,476.778412,0.982464,1442.459031,14.479177,361.174099,478.761897,313.279695,1.410391,0.526916,29099.324090,338.904295,0.817358,96.637123,0.669462,28746.619733,0.033080
min,3.000000e+06,200000.000000,200000.000000,1.000000,1.010000,1.000000,21.000000,200000.000000,10000.000000,1.000000,1.000000,-486.680000,3.000000,1.000000,400000.000000,1.000000,1128.490000,0.030100
25%,3.012346e+06,200411.000000,200407.000000,1.000000,1262.840000,13.000000,199.000000,200411.000000,10297.000000,2.000000,1.000000,23080.320000,361.000000,1.000000,400080.000000,1.000000,27771.850000,0.060700
50%,3.024684e+06,200811.000000,200815.000000,2.000000,2504.830000,26.000000,551.000000,200811.000000,10556.000000,3.000000,1.000000,49200.390000,648.000000,2.000000,400163.000000,1.000000,52339.530000,0.090200
75%,3.037126e+06,201239.000000,201232.000000,3.000000,3755.050000,38.000000,796.000000,201239.000000,10832.000000,4.000000,1.000000,74664.260000,927.000000,3.000000,400249.000000,2.000000,77030.490000,0.116500
max,3.049499e+06,201650.000000,201650.000000,4.000000,4999.590000,50.000000,1210.000000,201650.000000,11099.000000,5.000000,3.000000,99828.980000,1210.000000,3.000000,400329.000000,3.000000,99830.330000,0.150000

#### 5.6 Checking the data type and memory usage

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54955 entries, 0 to 54954
Data columns (total 35 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   TransactionID         54955 non-null  int64
 1   AccountOriginID       54955 non-null  int64
 2   AccountDestinationID  54955 non-null  int64
 3   TransactionTypeID     54955 non-null  int64
 4   Amount                54955 non-null  float64
 5   TransactionDate       53849 non-null  object
 6   BranchID              54955 non-null  int64
 7   Description           54955 non-null  object
 8   TypeName_x            54955 non-null  object
 9   BranchName            54955 non-null  object
 10  AddressID_x           54955 non-null  int64
 11  AccountID             54955 non-null  int64
 12  CustomerID            54955 non-null  int64
 13  AccountTypeID         54955 non-null  int64
 14  AccountStatusID       54955 non-null  int64
 15  Balance               54955 non-null  float64
 16  OpeningDate           53811 non-null  object
 17  TypeName_y            54955 non-null  object
 18  StatusName_x          54955 non-null  object
 19  FirstName             54109 non-null  object
 20  LastName              54012 non-null  object
 21  DateOfBirth           54955 non-null  object
 22  AddressID_y           54955 non-null  int64
 23  CustomerTypeID        54955 non-null  int64
 24  TypeName              54955 non-null  object
 25  Street                54196 non-null  object
 26  City                  53650 non-null  object
 27  Country               53760 non-null  object
 28  LoanID                11219 non-null  float64
 29  LoanStatusID          11219 non-null  float64
 30  PrincipalAmount       11219 non-null  float64
 31  InterestRate          11219 non-null  float64
 32  StartDate             11034 non-null  object
 33  EstimatedEndDate      11016 non-null  object
 34  StatusName_y          11219 non-null  object
dtypes: float64(6), int64(12), object(17)
memory usage: 14.7+ MB

## Step 6: Initial Missing Value Analysis (Before Cleaning)

In [78]:
df.isnull().sum().sort_values()

TransactionID               0
TypeName                    0
CustomerTypeID              0
AddressID_y                 0
DateOfBirth                 0
StatusName_x                0
Balance                     0
AccountStatusID             0
AccountTypeID               0
CustomerID                  0
AccountID                   0
TypeName_y                  0
BranchName                  0
AccountOriginID             0
AddressID_x                 0
TransactionTypeID           0
Amount                      0
AccountDestinationID        0
BranchID                    0
Description                 0
TypeName_x                  0
Street                    759
FirstName                 846
LastName                  943
TransactionDate          1106
OpeningDate              1144
Country                  1195
City                     1305
LoanID                  43736
LoanStatusID            43736
PrincipalAmount         43736
InterestRate            43736
StatusName_y            43736
StartDate               43921
EstimatedEndDate        43939
dtype: int64

In [79]:
## Checking missing values in percentage in the data set
(df.isnull().sum()/len(df))*100

TransactionID            0.000000
AccountOriginID          0.000000
AccountDestinationID     0.000000
TransactionTypeID        0.000000
Amount                   0.000000
TransactionDate          2.012556
BranchID                 0.000000
Description              0.000000
TypeName_x               0.000000
BranchName               0.000000
AddressID_x              0.000000
AccountID                0.000000
CustomerID               0.000000
AccountTypeID            0.000000
AccountStatusID          0.000000
Balance                  0.000000
OpeningDate              2.081703
TypeName_y               0.000000
StatusName_x             0.000000
FirstName                1.539441
LastName                 1.715949
DateOfBirth              0.000000
AddressID_y              0.000000
CustomerTypeID           0.000000
TypeName                 0.000000
Street                   1.381130
City                     2.374670
Country                  2.174506
LoanID                  79.585115
LoanStatusID            79.585115
PrincipalAmount         79.585115
InterestRate            79.585115
StartDate               79.921754
EstimatedEndDate        79.954508
StatusName_y            79.585115
dtype: float64

#### Step 7: Converting date columns

In [80]:
date_cols = ['TransactionDate','OpeningDate','StartDate','EstimatedEndDate','DateOfBirth']

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

### Step 8: Data Cleaning & Preprocessing

#### 8.1 Renaming the columnns

In [81]:
df = df.rename(columns={"TypeName_x":"TransactionType","TypeName_y":"AccountType","TypeName":"CustomerType","StatusName_x":"AccountStatus","StatusName_y":"LoanStatus"})

In [82]:
df.columns

Index(['TransactionID', 'AccountOriginID', 'AccountDestinationID',
       'TransactionTypeID', 'Amount', 'TransactionDate', 'BranchID',
       'Description', 'TransactionType', 'BranchName', 'AddressID_x',
       'AccountID', 'CustomerID', 'AccountTypeID', 'AccountStatusID',
       'Balance', 'OpeningDate', 'AccountType', 'AccountStatus', 'FirstName',
       'LastName', 'DateOfBirth', 'AddressID_y', 'CustomerTypeID',
       'CustomerType', 'Street', 'City', 'Country', 'LoanID', 'LoanStatusID',
       'PrincipalAmount', 'InterestRate', 'StartDate', 'EstimatedEndDate',
       'LoanStatus'],
      dtype='object')

#### 8.2 Creating new features
- Loan Duration Days: Calculated by finding the difference between EstimatedEndDate and StartDate, representing the total duration of each loan in days.
- Transaction Year: Extracted from TransactionDate to analyze transaction patterns across different years.
- Transaction Month: Extracted from TransactionDate to study monthly transaction trends and seasonal patterns.
- Customer Age: Computed using the difference between the current date and DateOfBirth to analyze customer demographics and financial behavior across age groups.

In [83]:
df['LoanDurationDays'] = (df['EstimatedEndDate'] - df['StartDate']).dt.days
df['TransactionYear'] = df['TransactionDate'].dt.year
df['TransactionMonth'] = df['TransactionDate'].dt.month
df['CustomerAge'] = (pd.Timestamp.now() - df['DateOfBirth']).dt.days // 365

In [84]:
df.columns

Index(['TransactionID', 'AccountOriginID', 'AccountDestinationID',
       'TransactionTypeID', 'Amount', 'TransactionDate', 'BranchID',
       'Description', 'TransactionType', 'BranchName', 'AddressID_x',
       'AccountID', 'CustomerID', 'AccountTypeID', 'AccountStatusID',
       'Balance', 'OpeningDate', 'AccountType', 'AccountStatus', 'FirstName',
       'LastName', 'DateOfBirth', 'AddressID_y', 'CustomerTypeID',
       'CustomerType', 'Street', 'City', 'Country', 'LoanID', 'LoanStatusID',
       'PrincipalAmount', 'InterestRate', 'StartDate', 'EstimatedEndDate',
       'LoanStatus', 'LoanDurationDays', 'TransactionYear', 'TransactionMonth',
       'CustomerAge'],
      dtype='object')

## 8.3 Handling Missing Values in the dataset

#### 8.3.1. Loan related missing values
- Principal Amount: Missing values in the PrincipalAmount column were replaced with 0, as many transactions in the dataset are not linked to a loan, meaning there is no principal amount involved.

- Interest Rate: Missing values in the InterestRate column were filled with 0 to indicate that no interest rate applies when a loan is not present.

- Loan Duration Days: Any missing values in the LoanDurationDays column were set to 0, showing that the transaction or account does not have an associated loan duration.

- Loan Status: Missing values in the LoanStatus column were replaced with "No Loan" to clearly reflect that the customer or account does not currently have a loan.

In [85]:
df['PrincipalAmount'] = df['PrincipalAmount'].fillna(0)
df['InterestRate'] = df['InterestRate'].fillna(0)
df['LoanDurationDays'] = df['LoanDurationDays'].fillna(0)
df['LoanStatus'] = df['LoanStatus'].fillna("No Loan")

#### 8.3.2 Handling Missing Address Information

- Missing values in the Street, City, and Country columns were replaced with "Unknown" to indicate that the address details were not available in the dataset.

- This approach helps retain all records in the dataset while clearly marking where location information is missing.

In [86]:
address_cols = ['Street','City','Country']

for col in address_cols:
    df[col] = df[col].fillna("Unknown")

#### 8.3.3 Handling Missing Customer Names
- Missing values in the FirstName and LastName columns were replaced with "Unknown" to indicate that the customer's name information was not available in the dataset.

- This ensures that all records remain in the dataset while clearly marking where customer name details are missing.

In [87]:
df['FirstName'] = df['FirstName'].fillna("Unknown")
df['LastName'] = df['LastName'].fillna("Unknown")

#### 8.3.4 Handling Missing Transaction Dates

- Records with missing values in the TransactionDate column were removed from the dataset.
- Since the transaction date is essential for time-based analysis, rows without this information were dropped to ensure accurate temporal analysis.

In [88]:
df = df.dropna(subset=['TransactionDate'])

#### 8.3.5  Handling Opening Date Missing Values

- Missing values in the OpeningDate column were filled using the median opening date from the dataset.
- This helps keep the dataset complete while maintaining a realistic representation of when most accounts were opened.

In [89]:
df['OpeningDate'] = df['OpeningDate'].fillna(df['OpeningDate'].median())

#### 8.3.4 Handling Missing Customer Age
- Missing values in the CustomerAge column were replaced with the median age of customers in the dataset.
- Using the median helps keep the data realistic while preventing missing values from affecting further analysis.

In [90]:
df['CustomerAge']=df['CustomerAge'].fillna(df['CustomerAge'].median())

## Step 9 Checking Duplicates

In [91]:
df.duplicated().sum()

np.int64(4284)

In [92]:
df = df.drop_duplicates()

In [93]:
# Rechecking the duplicated values
df.duplicated().sum()

np.int64(0)

In [94]:
df.columns

Index(['TransactionID', 'AccountOriginID', 'AccountDestinationID',
       'TransactionTypeID', 'Amount', 'TransactionDate', 'BranchID',
       'Description', 'TransactionType', 'BranchName', 'AddressID_x',
       'AccountID', 'CustomerID', 'AccountTypeID', 'AccountStatusID',
       'Balance', 'OpeningDate', 'AccountType', 'AccountStatus', 'FirstName',
       'LastName', 'DateOfBirth', 'AddressID_y', 'CustomerTypeID',
       'CustomerType', 'Street', 'City', 'Country', 'LoanID', 'LoanStatusID',
       'PrincipalAmount', 'InterestRate', 'StartDate', 'EstimatedEndDate',
       'LoanStatus', 'LoanDurationDays', 'TransactionYear', 'TransactionMonth',
       'CustomerAge'],
      dtype='object')

In [95]:
df.describe()

,TransactionID,AccountOriginID,AccountDestinationID,TransactionTypeID,Amount,TransactionDate,BranchID,AddressID_x,AccountID,CustomerID,...,LoanID,LoanStatusID,PrincipalAmount,InterestRate,StartDate,EstimatedEndDate,LoanDurationDays,TransactionYear,TransactionMonth,CustomerAge
count,4.956500e+04,49565.000000,49565.000000,49565.000000,49565.000000,49565,49565.000000,49565.000000,49565.000000,49565.000000,...,10137.000000,10137.000000,49565.000000,49565.000000,9956,9939,49565.000000,49565.000000,49565.000000,49565.000000
mean,3.024724e+06,200824.265671,200818.775325,2.194835,2503.630845,2022-02-01 14:42:42.385043456,25.625744,540.880742,200824.265671,10552.561566,...,400164.155865,1.384039,10575.193868,0.018326,2022-02-24 06:13:16.239004928,2025-03-04 07:37:01.981845760,220.017654,2021.595602,6.420397,44.750651
min,3.000000e+06,200000.000000,200000.000000,1.000000,1.010000,2020-01-01 00:00:00,1.000000,21.000000,200000.000000,10000.000000,...,400000.000000,1.000000,0.000000,0.000000,2021-01-01 00:00:00,2022-01-25 00:00:00,-658.000000,2020.000000,1.000000,-1.000000
25%,3.012353e+06,200413.000000,200407.000000,1.000000,1261.440000,2021-01-10 11:00:00,13.000000,199.000000,200413.000000,10296.000000,...,400081.000000,1.000000,0.000000,0.000000,2021-07-13 00:00:00,2024-02-11 00:00:00,0.000000,2021.000000,3.000000,35.000000
50%,3.024726e+06,200819.000000,200814.000000,2.000000,2503.940000,2022-01-24 14:00:00,26.000000,551.000000,200819.000000,10549.000000,...,400163.000000,1.000000,0.000000,0.000000,2022-02-20 00:00:00,2025-02-20 00:00:00,0.000000,2022.000000,6.000000,45.000000
75%,3.037111e+06,201241.000000,201230.000000,3.000000,3753.490000,2023-02-04 09:00:00,38.000000,796.000000,201241.000000,10819.000000,...,400247.000000,2.000000,0.000000,0.000000,2022-09-25 00:00:00,2026-04-18 00:00:00,0.000000,2023.000000,9.000000,56.000000
max,3.049499e+06,201650.000000,201650.000000,4.000000,4999.590000,2026-08-28 15:01:43.084879,50.000000,1210.000000,201650.000000,11099.000000,...,400329.000000,3.000000,99830.330000,0.150000,2026-08-29 15:01:44.338382,2028-01-12 00:00:00,1823.000000,2026.000000,12.000000,66.000000
std,1.430160e+04,476.958599,476.257287,0.983127,1442.160600,NaN,14.480975,361.122194,476.958599,310.818698,...,95.679990,0.665559,24554.785311,0.039069,NaN,NaN,486.667194,1.236290,3.507285,12.660545

## Rechecking for missing values

In [97]:
(df.isnull().sum()/len(df))*100

TransactionID            0.000000
AccountOriginID          0.000000
AccountDestinationID     0.000000
TransactionTypeID        0.000000
Amount                   0.000000
TransactionDate          0.000000
BranchID                 0.000000
Description              0.000000
TransactionType          0.000000
BranchName               0.000000
AddressID_x              0.000000
AccountID                0.000000
CustomerID               0.000000
AccountTypeID            0.000000
AccountStatusID          0.000000
Balance                  0.000000
OpeningDate              0.000000
AccountType              0.000000
AccountStatus            0.000000
FirstName                0.000000
LastName                 0.000000
DateOfBirth              3.415717
AddressID_y              0.000000
CustomerTypeID           0.000000
CustomerType             0.000000
Street                   0.000000
City                     0.000000
Country                  0.000000
LoanID                  79.548068
LoanStatusID            79.548068
PrincipalAmount          0.000000
InterestRate             0.000000
StartDate               79.913245
EstimatedEndDate        79.947544
LoanStatus               0.000000
LoanDurationDays         0.000000
TransactionYear          0.000000
TransactionMonth         0.000000
CustomerAge              0.000000
dtype: float64

# Handling the remaining missing values

- Date of Birth: Missing values were filled using the median date of birth to keep the age distribution realistic.

- Loan ID: Missing values were replaced with 0, indicating that the account does not have a loan.

- Loan Status ID: Missing values were filled with 0 to show that no loan is associated with those records.

- Loan Start Date: Missing values were replaced with a placeholder date to represent accounts without loans.

- Loan End Date: Missing values were also filled with a placeholder date for consistency.

- Loan Duration: Missing values in loan duration were set to 0, indicating that no loan duration exists.

In [99]:
df['DateOfBirth'] = df['DateOfBirth'].fillna(df['DateOfBirth'].median())

In [100]:
df['LoanID'] = df['LoanID'].fillna(0)

In [101]:
df['LoanStatusID'] = df['LoanStatusID'].fillna(0)

In [102]:
df['StartDate'] = df['StartDate'].fillna(pd.Timestamp("1900-01-01"))

In [103]:
df['EstimatedEndDate'] = df['EstimatedEndDate'].fillna(pd.Timestamp("1900-01-01"))

#### final data set check

In [104]:
(df.isnull().sum()/len(df))*100

TransactionID           0.0
AccountOriginID         0.0
AccountDestinationID    0.0
TransactionTypeID       0.0
Amount                  0.0
TransactionDate         0.0
BranchID                0.0
Description             0.0
TransactionType         0.0
BranchName              0.0
AddressID_x             0.0
AccountID               0.0
CustomerID              0.0
AccountTypeID           0.0
AccountStatusID         0.0
Balance                 0.0
OpeningDate             0.0
AccountType             0.0
AccountStatus           0.0
FirstName               0.0
LastName                0.0
DateOfBirth             0.0
AddressID_y             0.0
CustomerTypeID          0.0
CustomerType            0.0
Street                  0.0
City                    0.0
Country                 0.0
LoanID                  0.0
LoanStatusID            0.0
PrincipalAmount         0.0
InterestRate            0.0
StartDate               0.0
EstimatedEndDate        0.0
LoanStatus              0.0
LoanDurationDays        0.0
TransactionYear         0.0
TransactionMonth        0.0
CustomerAge             0.0
dtype: float64

#### Now our data is clean and ready for analysis

In [105]:
df.to_csv("C:/Users/shubh/Desktop/Simran/Project/Prodigy-info-tech/Project-2/Finance_Fraud&Loan_Dataset/finance_fraud_cleaned_dataset.csv", index=False)